import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Navbar from "../components/Navbar";
import Footer from "../components/Footer";
import PokemonList from "../components/PokemonList";
import PaginationButton from "../components/PaginationButton";
import { useState } from "react";

const url = "https://pokeapi.co/api/v2/pokemon/";

export default function Home({ data }) {
  const [pokemonList, setPokemonList] = useState(data);

  const prevHandleClick =async()=>{
    const response = await fetch(pokemonList.previous)
    const result = await response.json()

    setPokemonList(result)
  }

  const nextHandleClick = async()=>{
    const response = await fetch(pokemonList.next)
    const result = await response.json()

    setPokemonList(result)
  }

  return (
    <div className="mw-100">
      <Head>
        <title>Pokemon</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />
      <PokemonList pokemonList={pokemonList} prev={prevHandleClick} next={nextHandleClick}/>
      <Footer />
    </div>
  );
}

export async function getStaticProps(context) {
  const response = await fetch("https://pokeapi.co/api/v2/pokemon/");
  const data = await response.json();

  console.log(data);

  return {
    props: {
      data,
    },
  };
}
